name: mumu_project
description: "project mumu"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.2
  cupertino_icons: ^1.0.5
  responsive_framework: ^1.1.0
  page_transition: ^2.0.9
  fluttertoast: ^8.2.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.3.2
  sliding_switch: ^1.1.0
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.0.15
  flutter_phoenix: ^1.1.1
  url_launcher: ^6.1.12
  flutter_svg_provider: ^1.0.6
  dotted_line: ^3.2.2
  rflutter_alert: ^2.0.7
  flutter_launcher_icons: ^0.13.1
  quiver: ^3.2.1
  expandable: ^5.0.1
  intl: ^0.18.0
  http: ^1.0.0 
 
  geolocator: ^10.1.0
  permission_handler: ^11.0.0 
  dropdown_button2: ^2.0.0
  flutter_easyloading: ^3.0.5
  font_awesome_flutter: ^10.8.0
  multi_select_flutter: ^4.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt-Regular.ttf

